/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RentalContractManager } from "./RentalContractManager";
export * as factories from "./factories";
export { RentalContractManager__factory } from "./factories/RentalContractManager__factory";
