/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RentalContractManager {
  export type ContractInfoStruct = {
    contractHash: BytesLike;
    landlord: AddressLike;
    tenant: AddressLike;
    timestamp: BigNumberish;
    isActive: boolean;
    landlordSigned: boolean;
    tenantSigned: boolean;
    depositAmount: BigNumberish;
    monthlyRent: BigNumberish;
    depositPaid: boolean;
    depositRefunded: boolean;
    totalPaid: BigNumberish;
  };

  export type ContractInfoStructOutput = [
    contractHash: string,
    landlord: string,
    tenant: string,
    timestamp: bigint,
    isActive: boolean,
    landlordSigned: boolean,
    tenantSigned: boolean,
    depositAmount: bigint,
    monthlyRent: bigint,
    depositPaid: boolean,
    depositRefunded: boolean,
    totalPaid: bigint
  ] & {
    contractHash: string;
    landlord: string;
    tenant: string;
    timestamp: bigint;
    isActive: boolean;
    landlordSigned: boolean;
    tenantSigned: boolean;
    depositAmount: bigint;
    monthlyRent: bigint;
    depositPaid: boolean;
    depositRefunded: boolean;
    totalPaid: bigint;
  };
}

export interface RentalContractManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contractHashes"
      | "contracts"
      | "createContract"
      | "getAllContractHashes"
      | "getContract"
      | "getContractsByUser"
      | "getTotalContracts"
      | "markDepositPaid"
      | "markDepositRefunded"
      | "recordRentPayment"
      | "signContract"
      | "terminateContract"
      | "verifyContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractCreated"
      | "ContractFullySigned"
      | "ContractSigned"
      | "ContractTerminated"
      | "DepositPaid"
      | "DepositRefunded"
      | "RentPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contractHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contracts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createContract",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllContractHashes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markDepositPaid",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDepositRefunded",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRentPayment",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyContract",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "contractHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllContractHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDepositPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDepositRefunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRentPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyContract",
    data: BytesLike
  ): Result;
}

export namespace ContractCreatedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    landlord: AddressLike,
    tenant: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    landlord: string,
    tenant: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    landlord: string;
    tenant: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractFullySignedEvent {
  export type InputTuple = [contractHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [contractHash: string, timestamp: bigint];
  export interface OutputObject {
    contractHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractSignedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    signer: AddressLike,
    isLandlord: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    signer: string,
    isLandlord: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    signer: string;
    isLandlord: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractTerminatedEvent {
  export type InputTuple = [contractHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [contractHash: string, timestamp: bigint];
  export interface OutputObject {
    contractHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositPaidEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    payer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    payer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    payer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRefundedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    receiver: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    receiver: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    receiver: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentPaidEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    payer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    payer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    payer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RentalContractManager extends BaseContract {
  connect(runner?: ContractRunner | null): RentalContractManager;
  waitForDeployment(): Promise<this>;

  interface: RentalContractManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contractHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  contracts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        contractHash: string;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isActive: boolean;
        landlordSigned: boolean;
        tenantSigned: boolean;
        depositAmount: bigint;
        monthlyRent: bigint;
        depositPaid: boolean;
        depositRefunded: boolean;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  createContract: TypedContractMethod<
    [
      _contractHash: BytesLike,
      _tenant: AddressLike,
      _depositAmount: BigNumberish,
      _monthlyRent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllContractHashes: TypedContractMethod<[], [string[]], "view">;

  getContract: TypedContractMethod<
    [_contractHash: BytesLike],
    [RentalContractManager.ContractInfoStructOutput],
    "view"
  >;

  getContractsByUser: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  getTotalContracts: TypedContractMethod<[], [bigint], "view">;

  markDepositPaid: TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  markDepositRefunded: TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordRentPayment: TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  signContract: TypedContractMethod<
    [_contractHash: BytesLike],
    [void],
    "nonpayable"
  >;

  terminateContract: TypedContractMethod<
    [_contractHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyContract: TypedContractMethod<
    [_contractHash: BytesLike],
    [
      [boolean, boolean, string, string, bigint, boolean, boolean] & {
        exists: boolean;
        isActive: boolean;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        landlordSigned: boolean;
        tenantSigned: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contractHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        contractHash: string;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isActive: boolean;
        landlordSigned: boolean;
        tenantSigned: boolean;
        depositAmount: bigint;
        monthlyRent: bigint;
        depositPaid: boolean;
        depositRefunded: boolean;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createContract"
  ): TypedContractMethod<
    [
      _contractHash: BytesLike,
      _tenant: AddressLike,
      _depositAmount: BigNumberish,
      _monthlyRent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllContractHashes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [_contractHash: BytesLike],
    [RentalContractManager.ContractInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractsByUser"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalContracts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markDepositPaid"
  ): TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markDepositRefunded"
  ): TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordRentPayment"
  ): TypedContractMethod<
    [_contractHash: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signContract"
  ): TypedContractMethod<[_contractHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "terminateContract"
  ): TypedContractMethod<[_contractHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyContract"
  ): TypedContractMethod<
    [_contractHash: BytesLike],
    [
      [boolean, boolean, string, string, bigint, boolean, boolean] & {
        exists: boolean;
        isActive: boolean;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        landlordSigned: boolean;
        tenantSigned: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ContractCreated"
  ): TypedContractEvent<
    ContractCreatedEvent.InputTuple,
    ContractCreatedEvent.OutputTuple,
    ContractCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractFullySigned"
  ): TypedContractEvent<
    ContractFullySignedEvent.InputTuple,
    ContractFullySignedEvent.OutputTuple,
    ContractFullySignedEvent.OutputObject
  >;
  getEvent(
    key: "ContractSigned"
  ): TypedContractEvent<
    ContractSignedEvent.InputTuple,
    ContractSignedEvent.OutputTuple,
    ContractSignedEvent.OutputObject
  >;
  getEvent(
    key: "ContractTerminated"
  ): TypedContractEvent<
    ContractTerminatedEvent.InputTuple,
    ContractTerminatedEvent.OutputTuple,
    ContractTerminatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositPaid"
  ): TypedContractEvent<
    DepositPaidEvent.InputTuple,
    DepositPaidEvent.OutputTuple,
    DepositPaidEvent.OutputObject
  >;
  getEvent(
    key: "DepositRefunded"
  ): TypedContractEvent<
    DepositRefundedEvent.InputTuple,
    DepositRefundedEvent.OutputTuple,
    DepositRefundedEvent.OutputObject
  >;
  getEvent(
    key: "RentPaid"
  ): TypedContractEvent<
    RentPaidEvent.InputTuple,
    RentPaidEvent.OutputTuple,
    RentPaidEvent.OutputObject
  >;

  filters: {
    "ContractCreated(bytes32,address,address,uint256)": TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;
    ContractCreated: TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;

    "ContractFullySigned(bytes32,uint256)": TypedContractEvent<
      ContractFullySignedEvent.InputTuple,
      ContractFullySignedEvent.OutputTuple,
      ContractFullySignedEvent.OutputObject
    >;
    ContractFullySigned: TypedContractEvent<
      ContractFullySignedEvent.InputTuple,
      ContractFullySignedEvent.OutputTuple,
      ContractFullySignedEvent.OutputObject
    >;

    "ContractSigned(bytes32,address,bool,uint256)": TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;
    ContractSigned: TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;

    "ContractTerminated(bytes32,uint256)": TypedContractEvent<
      ContractTerminatedEvent.InputTuple,
      ContractTerminatedEvent.OutputTuple,
      ContractTerminatedEvent.OutputObject
    >;
    ContractTerminated: TypedContractEvent<
      ContractTerminatedEvent.InputTuple,
      ContractTerminatedEvent.OutputTuple,
      ContractTerminatedEvent.OutputObject
    >;

    "DepositPaid(bytes32,address,uint256,uint256)": TypedContractEvent<
      DepositPaidEvent.InputTuple,
      DepositPaidEvent.OutputTuple,
      DepositPaidEvent.OutputObject
    >;
    DepositPaid: TypedContractEvent<
      DepositPaidEvent.InputTuple,
      DepositPaidEvent.OutputTuple,
      DepositPaidEvent.OutputObject
    >;

    "DepositRefunded(bytes32,address,uint256,uint256)": TypedContractEvent<
      DepositRefundedEvent.InputTuple,
      DepositRefundedEvent.OutputTuple,
      DepositRefundedEvent.OutputObject
    >;
    DepositRefunded: TypedContractEvent<
      DepositRefundedEvent.InputTuple,
      DepositRefundedEvent.OutputTuple,
      DepositRefundedEvent.OutputObject
    >;

    "RentPaid(bytes32,address,uint256,uint256)": TypedContractEvent<
      RentPaidEvent.InputTuple,
      RentPaidEvent.OutputTuple,
      RentPaidEvent.OutputObject
    >;
    RentPaid: TypedContractEvent<
      RentPaidEvent.InputTuple,
      RentPaidEvent.OutputTuple,
      RentPaidEvent.OutputObject
    >;
  };
}
